# Generated by Django 4.0.2 on 2022-11-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appoinment_date',
            field=models.DateField(),
        ),
    ]
